add deploy token to scripts

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -102,12 +102,17 @@ jobs:
           username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
           key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
           script: |
+            if [ ! ${{ secrets.DEPLOY_PAT }} ]; then
+              echo "The DEPLOY_PAT secret is required to deploy"
+              exit 1
+            fi
+
             # Create a sparse checkout of the repo if it doesn't exist
             if [ ! -d "/home/marcus/projects/mock-my-draft" ]; then
               mkdir -p /home/marcus/projects/mock-my-draft
               cd /home/marcus/projects/mock-my-draft
               git init
-              git remote add origin git@github.com:schimizzimj/mock-my-draft.git
+              git remote add origin https://${{ secrets.DEPLOY_PAT }}@github.com/schimizzimj/mock-my-draft.git
               git config core.sparseCheckout true
               echo "docker-compose.base.yml" >> .git/info/sparse-checkout
               echo "docker-compose.prod.yml" >> .git/info/sparse-checkout
@@ -117,7 +122,7 @@ jobs:
 
             # Pull the latest changes
             cd /home/marcus/projects/mock-my-draft
-            git pull origin main
+            git pull https://${{ secrets.DEPLOY_PAT }}@github.com/schimizzimj/mock-my-draft.git main
 
             if [ ${{ github.event.inputs.rollback }} == 'true' ]; then
               chmod +x scripts/rollback.sh
